9 спринт
pavelrk97/java-kanban pull request #3
Opened 2024-12-16 20:02 UTC by pavelrk97

2024-12-18 23:38 UTC, NikolaiDem requested changes

2024-12-18 23:38 UTC, NikolaiDem commented on src/handlers/BaseHttpHandler.java
> +            e.printStackTrace();
Это code smells, так как логирование в консоль. Лучше использовать log.error(...)
Аналогично везде

2024-12-18 23:38 UTC, NikolaiDem commented on src/handlers/BaseHttpHandler.java
> +        try {
Лучше так:
try (h) {
            byte[] resp = text.getBytes(StandardCharsets.UTF_8);
            h.getResponseHeaders().add("Content-Type", "application/json;charset=utf-8");
            h.sendResponseHeaders(code, resp.length);
            h.getResponseBody().write(resp);
            h.close();
        }

2024-12-18 23:38 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +            ex.getMessage();
А что здесь ожидалось?

2024-12-18 23:38 UTC, NikolaiDem commented on src/managers/InMemoryHistoryManager.java
> +            System.out.println("History is empty");
Лучше везде использовать логгер

2024-12-18 23:38 UTC, NikolaiDem commented on src/managers/TaskManager.java
> +    void deleteEpicSubtasks(Integer epicId);
Метод лишний

2024-12-18 23:38 UTC, NikolaiDem commented on src/managers/TaskManager.java
> +    HistoryManager getHistoryManager();
Нужен метод, возвращающий список исторических задач

2024-12-18 23:38 UTC, NikolaiDem commented on src/type/adapters/DurationAdapter.java
> +        return Duration.parse(jsonReader.nextString());
А если null?

2024-12-19 13:02 UTC, pavelrk97 commented on src/managers/TaskManager.java
> +    HistoryManager getHistoryManager();
метод в интерфейсе HistoryManager

2024-12-19 13:04 UTC, pavelrk97 commented on src/managers/TaskManager.java
> +    HistoryManager getHistoryManager();
метод реализован в интерфейсе HistoryManager

2024-12-19 13:24 UTC, pavelrk97 commented on src/managers/TaskManager.java
> +    void deleteEpicSubtasks(Integer epicId);
Почему лишний? У пользователя ж есть возможность удалить все сабтаски одним нажатием, значит и таск менеджера должен быть такой метод и интерфейс? Ну и в тесте так уже реализован

2024-12-20 14:34 UTC, NikolaiDem approved these changes

2024-12-20 17:54 UTC, merged