Sprint 7 solution in file manager
pavelrk97/java-kanban pull request #6
Opened 2024-10-08 20:31 UTC by pavelrk97

2024-10-08 20:44 UTC, pavelrk97 commented
Кажется я немного отставать начал 🥇

2024-10-09 16:18 UTC, NikolaiDem requested changes

2024-10-09 16:18 UTC, NikolaiDem commented on src/managers/ExceptionsManager.java
> +public class ExceptionsManager extends RuntimeException {
Лучше называть исключение по причине, из-за которой оно возникает

2024-10-09 16:18 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +            for (Integer key : tasks.keySet()) {
Можно проще:
            for (var task : tasks.values()) {}

2024-10-09 16:18 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +                parsedTask.setStatus(status);
а статус можно сразу в конструктор передать?

2024-10-09 16:18 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    }
А переопределение методов удаления всех тасок, сабтасок и эпиков?

2024-10-09 16:18 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +    protected static Map<Integer, Task> tasks;
Для чего static?

2024-10-09 16:18 UTC, NikolaiDem commented on test/testsForTZ/FileBackedTaskManagerTest.java
> +public class FileBackedTaskManagerTest {
Отсутствуют тесты на проверку файлового менеджера, созданного из непустого файла

2024-10-10 11:23 UTC, pavelrk97 commented on src/managers/InMemoryTaskManager.java
> +    protected static Map<Integer, Task> tasks;
Предложила это IDEA, но я как понял, так как это "всеобщая" информация о том что в мапах, она должна быть более так сказать высокого уровня, чтобы проще к ней обращаться можно было

2024-10-10 15:44 UTC, NikolaiDem requested changes

2024-10-10 15:44 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +                        epics.put(id, epic);
Зачем повторно эпик складывать в мапу?

2024-10-10 15:44 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        } catch (FileNotFoundException exp) {
Лучше IllegalArgumentException
RuntimeException является слишком общим

2024-10-10 15:44 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        return task;
Нужно вернуть таску, которая была создана, а не передана в качестве аргумента.
Аналогично для эпиков и сабтасок

2024-10-10 15:44 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +    protected static Map<Integer, Task> tasks;
static не нужен. У каждого менеджера должен индивидуальный набор задач

2024-10-10 15:44 UTC, NikolaiDem commented on test/testsForTZ/FileBackedTaskManagerTest.java
> +public class FileBackedTaskManagerTest {
А где тесты на файловый менеджер, созданный из непустого файла?

2024-10-13 12:35 UTC, NikolaiDem commented on test/testsForTZ/FileBackedTaskManagerTest.java
> +        saveManager.createTask(new Task(1,"Задача 1", "Описание задачи 1", NEW));
Почему такой тест тоже работает?

        saveManager.createTask(new Task(1,"Задача 1", "Описание задачи 1", NEW));
        saveManager.createTask(new Task(2,"Задача 2", "Описание задачи 2", NEW));
        saveManager.createEpic(new Epic(3,"Эпик 1", "Описание эпика 1", NEW));
        saveManager.createSubtask(new Subtask(4,"Подзадача 1", "Описание подзадачи 1", NEW,3));

        loadManager = FileBackedTaskManager.loadFromFile(data);
        loadManager.createTask(new Task("Задача 5", "Описание задачи 1", NEW));
        loadManager.createTask(new Task("Задача 6", "Описание задачи 1", NEW));
        assertEquals(saveManager.getAllTasks(), loadManager.getAllTasks());
        assertEquals(saveManager.getAllEpics(), loadManager.getAllEpics());
        assertEquals(saveManager.getAllSubtasks(), loadManager.getAllSubtasks());

В loadManager 5 задач, а в saveManager 3 задачи, а тест все  еще работает

2024-10-13 16:39 UTC, NikolaiDem approved these changes

2024-11-26 11:02 UTC, merged